# Telegram Redirect for Quantumult X
# t.me → 第三方 Telegram 客户端重定向
# BoxJs key: telegram_redirect_client

hostname = t.me

^https?:\/\/t\.me\/.+ url script-echo-response https://github.com/JuemingDC/QuantumultX/raw/main/JavaScript/Telegram/TelegramRedirect.js
